-- Xóa toàn bộ bảng CrabFarmMonitor (public) — CHỈ dùng khi defaultdb bị schema cũ / lỗi FK
-- Chạy: apply-managed-db-schema.ps1 -Fresh

DROP TABLE IF EXISTS ai_alerts CASCADE;
DROP TABLE IF EXISTS ai_analysis_results CASCADE;
DROP TABLE IF EXISTS ai_models CASCADE;
DROP TABLE IF EXISTS camera_snapshots CASCADE;
DROP TABLE IF EXISTS camera_devices CASCADE;
DROP TABLE IF EXISTS sync_logs CASCADE;
DROP TABLE IF EXISTS alerts CASCADE;
DROP TABLE IF EXISTS sensor_readings CASCADE;
DROP TABLE IF EXISTS sensors CASCADE;
DROP TABLE IF EXISTS mqtt_configs CASCADE;
DROP TABLE IF EXISTS wifi_configs CASCADE;
DROP TABLE IF EXISTS gateways CASCADE;
DROP TABLE IF EXISTS harvests CASCADE;
DROP TABLE IF EXISTS health_records CASCADE;
DROP TABLE IF EXISTS feeding_logs CASCADE;
DROP TABLE IF EXISTS crab_values CASCADE;
DROP TABLE IF EXISTS crab_profiles CASCADE;
DROP TABLE IF EXISTS crabs CASCADE;
DROP TABLE IF EXISTS farming_batches CASCADE;
DROP TABLE IF EXISTS boxes CASCADE;
DROP TABLE IF EXISTS rows CASCADE;
DROP TABLE IF EXISTS areas CASCADE;
DROP TABLE IF EXISTS crab_individuals CASCADE;
DROP TABLE IF EXISTS crab_boxes CASCADE;
DROP TABLE IF EXISTS device_shadows CASCADE;
DROP TABLE IF EXISTS telemetry_samples CASCADE;
DROP TABLE IF EXISTS sync_jobs CASCADE;
DROP TABLE IF EXISTS hdf5_uploads CASCADE;
DROP TABLE IF EXISTS telemetry_latest CASCADE;
DROP TABLE IF EXISTS devices CASCADE;
DROP TABLE IF EXISTS users CASCADE;
DROP TABLE IF EXISTS farms CASCADE;
DROP TABLE IF EXISTS organizations CASCADE;
